{% set name = "apache-airflow-providers-opsgenie" %}
{% set version = "3.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: f757fdbfa38fbe99028687e10fef7ceb947d6663d5e8c41ab61c3060b47954ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - opsgenie-sdk >=2.1.5

test:
  imports:
    - airflow.providers.opsgenie
    - airflow.providers.opsgenie.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Opsgenie for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-opsgenie/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
