{% set name = "apache-airflow-providers-opsgenie" %}
{% set version = "5.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_opsgenie-{{ version }}.tar.gz
  sha256: 59dacca714cd20a61423cadc6a36737fd6aededbefb6fb526f13effb939e8efb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.9.0
    - opsgenie-sdk >=2.1.5

test:
  imports:
    - airflow.providers.opsgenie
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-opsgenie for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/opsgenie/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-opsgenie/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
