{% set name = "apache-airflow-providers-opsgenie" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-opsgenie-{{ version }}.tar.gz
  sha256: 85ff20407fd2536b8abf802533cf8af93673e7e5605948dd7bf9feacf980b88f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.2.0
    - pip
  run:
    - python >=3.7
    - apache-airflow >=2.4.0
    - opsgenie-sdk >=2.1.5

test:
  imports:
    - airflow.providers.opsgenie
    - airflow.providers.opsgenie.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-opsgenie package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-opsgenie/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
